// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDejgH5xs9zcnzoOcDmzojTiFKbhLKzruM',
    appId: '1:561793566465:web:fec7ace04962874d3a3d00',
    messagingSenderId: '561793566465',
    projectId: 'fir-learning-61ee7',
    authDomain: 'fir-learning-61ee7.firebaseapp.com',
    storageBucket: 'fir-learning-61ee7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD34ghGhOP-5tXOcuqSPgBF755Rfxikhbo',
    appId: '1:561793566465:android:25e2a26fcc9efa2b3a3d00',
    messagingSenderId: '561793566465',
    projectId: 'fir-learning-61ee7',
    storageBucket: 'fir-learning-61ee7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf1NFbvNR-xg-Xb60ry58o159UiiTJdgc',
    appId: '1:561793566465:ios:1ad85e8561d91e983a3d00',
    messagingSenderId: '561793566465',
    projectId: 'fir-learning-61ee7',
    storageBucket: 'fir-learning-61ee7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearning',
  );
}
